mongodb: 
    image: mongo
    command: --smallfiles

datastream:
    build: microservice-generic
    environment:
       - MICROSERVICE=datastream

auth:
    build: microservice-generic
    environment:
       - MICROSERVICE=auth
       - CUSTOMARGS=-DProd.mongodb.uri=mongodb://$MONGO_PORT_27017_TCP_ADDR:$MONGO_PORT_27017_TCP_PORT/auth
    links:
       - datastream:datastream.service
       - mongodb:mongo

ggstubs:
    build: microservice-generic
    environment:
       - MICROSERVICE=gg-stubs

gg:
    build: microservice-generic
    environment:
       - MICROSERVICE=government-gateway
       - CUSTOMARGS=-DProd.mongodb.uri=mongodb://$MONGO_PORT_27017_TCP_ADDR:$MONGO_PORT_27017_TCP_PORT/governmentgateway -DProd.microservice.services.external-government-gateway.host=gg-stubs.service -DProd.microservice.services.external-government-gateway.port=80 -DProd.microservice.services.external-government-gateway.protocol=http -DProd.ssoEncryptionKey=P5xsJ9Nt+quxGZzB4DeLfw==
    links:
       - datastream:datastream.service
       - mongodb:mongo
       - ggstubs:gg-stubs.service
       - auth:auth.service

authenticator:
    build: microservice-generic
    environment:
       - MICROSERVICE=authenticator
    links:
       - datastream:datastream.service
       - auth:auth.service
       - gg:government-gateway.service

companyauth:
    build: microservice-generic
    environment:
       - MICROSERVICE=company-auth-frontend
       - DOCKER_HOST_IP=dev.tax.service.gov.uk
       - CUSTOMARGS=-Dgovuk-tax.Prod.portal.url=http://$DOCKER_HOST_IP/portal -Dlogger.application=DEBUG -Dlogger.resource=/application-json-logger.xml
    links:
       - datastream:datastream.service
       - gg:government-gateway.service
       - auth:auth.service
       - authenticator:authenticator.service

ytastubs:
    build: microservice-generic
    environment:
       - MICROSERVICE=yta-stubs

cesastub:
    build: microservice-generic
    environment:
       - MICROSERVICE=cesa-stub

sa:
    build: microservice-generic
    environment:
       - MICROSERVICE=sa
    links:
       - datastream:datastream.service
       - cesastub:hods-proxy
       - auth:auth.service

vat:
    build: microservice-generic
    environment:
       - MICROSERVICE=vat
    links:
       - datastream:datastream.service
       - auth:auth.service
       - ytastubs:hods-proxy

ct:
    build: microservice-generic
    environment:
       - MICROSERVICE=ct
    links:
       - datastream:datastream.service
       - auth:auth.service
       - ytastubs:hods-proxy

epaye:
    build: microservice-generic
    environment:
       - MICROSERVICE=epaye
    links:
       - datastream:datastream.service
       - auth:auth.service
       - ytastubs:hods-proxy

businesstax:
    build: microservice-generic
    environment:
       - MICROSERVICE=business-tax-account
       - DOCKER_HOST_IP=dev.tax.service.gov.uk
       - CUSTOMARGS=-Dgovuk-tax.Prod.portal.url=http://$DOCKER_HOST_IP/portal
    links:
       - datastream:datastream.service
       - ytastubs:portal
       - auth:auth.service
       - gg:government-gateway.service
       - sa:sa.service
       - vat:vat.service
       - ct:ct.service
       - epaye:epaye.service

contact:
    build: microservice-generic
    environment:
       - MICROSERVICE=contact-frontend

save4later:
    build: microservice-generic
    environment:
       - MICROSERVICE=save4later
       - CUSTOMARGS=-DProd.mongodb.host=mongodb://$MONGO_PORT_27017_TCP_ADDR:$MONGO_PORT_27017_TCP_PORT

    links:
       - mongodb:mongo

taxaccountrouterfrontend:
    build: microservice-frontend
    environment:
       - MICROSERVICE=tax-account-router-frontend
       - VERSION=0.28.0
       - CUSTOMARGS=-Dauditing.consumer.baseUri.host=datastream.service -Dauditing.consumer.baseUri.port=80 -Dmicroservice.services.government-gateway.host=government-gateway.service -Dmicroservice.services.government-gateway.port=80 -Dmicroservice.services.auth.host=auth.service -Dmicroservice.services.auth.port=80 -Dmicroservice.services.sa.host=sa.service -Dmicroservice.services.sa.port=80 -Dmicroservice.services.cachable.short-lived-cache.host=save4later.service -Dmicroservice.services.cachable.short-lived-cache.port=80 -Dbusiness-tax-account.host=http://dev.tax.service.gov.uk -Dcompany-auth.host=http://dev.tax.service.gov.uk -Dcontact-frontend.host=http://dev.tax.service.gov.uk -Dtax-account-router.host=http://dev.tax.service.gov.uk -Dpersonal-tax-account.host=http://dev.tax.service.gov.uk
       - USE_SOURCE=true
    links:
       - datastream:datastream.service
       - save4later:save4later.service
       - sa:sa.service
       - auth:auth.service
       - gg:government-gateway.service
    volumes:
       - ~/Applications/hmrc-development-environment/hmrc/tax-account-router-frontend:/root/app
    ports:
      - "9280:80"

nginx:
    build: nginx
    links:
       - companyauth:company-auth-frontend.service
       - ytastubs:yta-stubs.service
       - businesstax:business-tax-account.service
       - contact:contact-frontend.service
       - taxaccountrouterfrontend:tax-account-router-frontend.service
    ports:
       - "80:80"
