mongodb: 
    image: mongo

datastream:
    build: microservice-generic
    environment:
       - MICROSERVICE=datastream

auth:
    build: microservice-generic
    environment:
       - MICROSERVICE=auth
       - CUSTOMARGS=-DProd.mongodb.uri=mongodb://$MONGO_PORT_27017_TCP_ADDR:$MONGO_PORT_27017_TCP_PORT/auth
    links:
       - datastream:datastream.service
       - mongodb:mongo

ggstubs:
    build: microservice-generic
    environment:
       - MICROSERVICE=gg-stubs

gg:
    build: microservice-generic
    environment:
       - MICROSERVICE=government-gateway
       - CUSTOMARGS=-DProd.mongodb.uri=mongodb://$MONGO_PORT_27017_TCP_ADDR:$MONGO_PORT_27017_TCP_PORT/governmentgateway -DProd.microservice.services.external-government-gateway.host=gg-stubs.service -DProd.microservice.services.external-government-gateway.port=80 -DProd.microservice.services.external-government-gateway.protocol=http -DProd.ssoEncryptionKey=P5xsJ9Nt+quxGZzB4DeLfw==
    links:
       - datastream:datastream.service
       - mongodb:mongo
       - ggstubs:gg-stubs.service
       - auth:auth.service

authenticator:
    build: microservice-generic
    environment:
       - MICROSERVICE=authenticator
    links:
       - datastream:datastream.service
       - auth:auth.service
       - gg:government-gateway.service

companyauth:
    build: microservice-generic
    environment:
       - MICROSERVICE=company-auth-frontend
       - DOCKER_HOST_IP=dev.tax.service.gov.uk
       - CUSTOMARGS=-Dgovuk-tax.Prod.portal.url=http://$DOCKER_HOST_IP/portal -Dlogger.application=DEBUG -Dlogger.resource=/application-json-logger.xml
    links:
       - datastream:datastream.service
       - gg:government-gateway.service
       - auth:auth.service
       - authenticator:authenticator.service

ytastubs:
    build: microservice-generic
    environment:
       - MICROSERVICE=yta-stubs

cesastub:
    build: microservice-generic
    environment:
       - MICROSERVICE=cesa-stub

sa:
    build: microservice-generic
    environment:
       - MICROSERVICE=sa
    links:
       - datastream:datastream.service
       - cesastub:hods-proxy
       - auth:auth.service

vat:
    build: microservice-generic
    environment:
       - MICROSERVICE=vat
    links:
       - datastream:datastream.service
       - auth:auth.service
       - ytastubs:hods-proxy

ct:
    build: microservice-generic
    environment:
       - MICROSERVICE=ct
    links:
       - datastream:datastream.service
       - auth:auth.service
       - ytastubs:hods-proxy

epaye:
    build: microservice-generic
    environment:
       - MICROSERVICE=epaye
    links:
       - datastream:datastream.service
       - auth:auth.service
       - ytastubs:hods-proxy

contact:
    build: microservice-generic
    environment:
       - MICROSERVICE=contact-frontend

nginx:
    build: nginx-local-dev
    links:
       - companyauth:company-auth-frontend.service
       - ytastubs:yta-stubs.service
       - contact:contact-frontend.service
       - auth:auth.service
       - authenticator:authenticator.service
       - gg:government-gateway.service
       - sa:sa.service
       - vat:vat.service
       - ct:ct.service
       - epaye:epaye.service
       - contact:contact-frontend.service
    ports:
       - "80:80"
